In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [117]:
 
data = {'name': ['ahmad', 'hamed', 'mona', 'syd', 'lbna'],
        'Weight': [70, 88, 91, 65, 79],
        'age': [18, 22, 38, 21, 25],
        'Anemia': [1, 0, 0, 1, 1],
        'sick': [1, 1, 1, 0, 0]}
df = pd.DataFrame(data)
df_x0=np.ones((5,1))
df.insert(1, "x0", df_x0)
 

In [118]:

def Classification(theta, alpha, m, x, x_T, y):
    def theta_dot_x(theta, x):
        theta_dot_x_result = np.dot(x, theta)
        return theta_dot_x_result

    def theta_dot_x_subtract_y(theta_dot_x, y):
        theta_dot_x_subtract = theta_dot_x - y.values.reshape(-1, 1)
        return theta_dot_x_subtract

    def dot_xT_by_theta_dot_x_subtract_y(theta_dot_x_subtract, x_T):
        dot_xT_by_theta_dot_x_subtract = np.dot(x_T, theta_dot_x_subtract)
        return dot_xT_by_theta_dot_x_subtract
    def dot_alph_m_dot_xT_by_theta_dot_x_subtract(m , alpha ,dot_xT_by_theta_dot_x_subtract_result):
        result = alpha/m 
        dot_alph_m_dot_xT_by_theta_dot_x_subtract = result* dot_xT_by_theta_dot_x_subtract_result 
        return dot_alph_m_dot_xT_by_theta_dot_x_subtract 
    def theta_gd( theta , dot_alph_m_dot_xT_by_theta_dot_x_subtract  ):
        theta = theta - dot_alph_m_dot_xT_by_theta_dot_x_subtract 
        return theta 
    theta_dot_x_result = theta_dot_x(theta, x)
    theta_dot_x_subtract_result = theta_dot_x_subtract_y(theta_dot_x_result, y)
    dot_xT_by_theta_dot_x_subtract_result = dot_xT_by_theta_dot_x_subtract_y(theta_dot_x_subtract_result, x_T)
    dot_alph_m_dot_xT_by_theta_dot_x_subtract = dot_alph_m_dot_xT_by_theta_dot_x_subtract(m , alpha ,dot_xT_by_theta_dot_x_subtract_result)
    theta_gd = theta_gd( theta , dot_alph_m_dot_xT_by_theta_dot_x_subtract  )
    print('theta_dot_x_result')
    print(theta_dot_x_result)
    print("---------------------")
    print("theta_dot_x_subtract_result")
    print(theta_dot_x_subtract_result)
    print("---------------------")
    print('dot_xT_by_theta_dot_x_subtract_result')
    print(dot_xT_by_theta_dot_x_subtract_result)
    print("---------------------")
    print('dot_alph_m_dot_xT_by_theta_dot_x_subtract')
    print(dot_alph_m_dot_xT_by_theta_dot_x_subtract)
    print("---------------------")
    print('theta_gd')
    print(theta_gd)

In [119]:

theta = np.ones((4,1))
x = df.drop(["name"], axis=1)
x = x.drop(["sick"], axis=1)

x_T = x.transpose()
y = df["sick"]
m = len(df)
alpha = 0.5


In [120]:

Classification(theta, alpha, m, x, x_T, y)


theta_dot_x_result
[[ 90.]
 [111.]
 [130.]
 [ 88.]
 [106.]]
---------------------
theta_dot_x_subtract_result
[[ 89.]
 [110.]
 [129.]
 [ 88.]
 [106.]]
---------------------
dot_xT_by_theta_dot_x_subtract_result
[[  522.]
 [41743.]
 [13422.]
 [  283.]]
---------------------
dot_alph_m_dot_xT_by_theta_dot_x_subtract
[[  52.2]
 [4174.3]
 [1342.2]
 [  28.3]]
---------------------
theta_gd
[[  -51.2]
 [-4173.3]
 [-1341.2]
 [  -27.3]]
